'use strict';

const STATUS_AWAITING_APPROVAL = 0;
const STATUS_ON_LIST = 1;
const STATUS_CHECKED_IN = 2;

module.exports = {
  STATUS_AWAITING_APPROVAL: STATUS_AWAITING_APPROVAL,
  STATUS_ON_LIST: STATUS_ON_LIST,
  STATUS_CHECKED_IN: STATUS_CHECKED_IN
}
